### ISSUE TITLE
Internal Server Error when Uploading Chineese VCards

### ISSUE THREAD

**Issue by rodja** [hoccer/server#3]
<pre><code>
Processing EventsController#create (for 80.187.111.254 at 2010-09-06 16:11:21) [POST]
  Parameters: {"event"=>{"brand"=>"google", "device"=>"passion", "model"=>"Nexus One", "bssids"=>"", "latitude"=>"52.520123", "network_type"=>"UMTS", "timestamp"=>"1283782249099", "network_operator"=>"Telekom.de", "client_uuid"=>"fb953302-d4b5-4291-b79e-5a3add349caf", "hoccability"=>"1", "location_accuracy"=>"518.0", "type"=>"SweepOut", "manufacturer"=>"HTC", "longitude"=>"13.407874", "local_ip"=>"10.216.135.254", "version_sdk"=>"8"}}
[paperclip] Saving attachments.
Redirected to http://beta.hoccer.com/events/8cc116b09bee012dbfd100176ed99fe3
Completed in 50ms (DB: 31) | 303 See Other [http://beta.hoccer.com/events]

Processing EventsController#show (for 80.187.111.254 at 2010-09-06 16:11:22) [GET]
  Parameters: {"id"=>"8cc116b09bee012dbfd100176ed99fe3"}
Completed in 40ms (View: 0, DB: 25) | 202 Accepted [http://beta.hoccer.com/events/8cc116b09bee012dbfd100176ed99fe3]

/!\ FAILSAFE /!\  Mon Sep 06 16:11:23 +0200 2010
  Status: 500 Internal Server Error
  undefined method `merge' for nil:NilClass
    /usr/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/request.rb:385:in `parameters'
    /usr/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:1288:in `assign_shortcuts'
    /usr/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:527:in `process_without_filters'
    /usr/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/filters.rb:606:in `process'
    /usr/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/rescue.rb:65:in `call_with_exception'
    /usr/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/dispatcher.rb:90:in `dispatch'
    /usr/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/dispatcher.rb:121:in `_call'
    /usr/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/dispatcher.rb:130:in `build_middleware_stack'
    /usr/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/query_cache.rb:29:in `call'
    /usr/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/query_cache.rb:29:in `call'
    /usr/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/connection_adapters/abstract/query_cache.rb:34:in `cache'
    /usr/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/query_cache.rb:9:in `cache'
    /usr/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/query_cache.rb:28:in `call'
    /usr/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:361:in `call'
    /usr/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/string_coercion.rb:25:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-1.0.1/lib/rack/head.rb:9:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-1.0.1/lib/rack/methodoverride.rb:24:in `call'
    /usr/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/params_parser.rb:15:in `call'
    /usr/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/session/cookie_store.rb:93:in `call'
    /usr/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/failsafe.rb:26:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-1.0.1/lib/rack/lock.rb:11:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-1.0.1/lib/rack/lock.rb:11:in `synchronize'
    /usr/lib/ruby/gems/1.8/gems/rack-1.0.1/lib/rack/lock.rb:11:in `call'
    /usr/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/dispatcher.rb:106:in `call'
    /usr/lib/ruby/gems/1.8/gems/passenger-2.2.9/lib/phusion_passenger/rack/request_handler.rb:92:in `process_request'
    /usr/lib/ruby/gems/1.8/gems/passenger-2.2.9/lib/phusion_passenger/abstract_request_handler.rb:207:in `main_loop'
    /usr/lib/ruby/gems/1.8/gems/passenger-2.2.9/lib/phusion_passenger/railz/application_spawner.rb:400:in `start_request_handler'
    /usr/lib/ruby/gems/1.8/gems/passenger-2.2.9/lib/phusion_passenger/railz/application_spawner.rb:351:in `handle_spawn_application'
    /usr/lib/ruby/gems/1.8/gems/passenger-2.2.9/lib/phusion_passenger/utils.rb:184:in `safe_fork'
    /usr/lib/ruby/gems/1.8/gems/passenger-2.2.9/lib/phusion_passenger/railz/application_spawner.rb:349:in `handle_spawn_application'
    /usr/lib/ruby/gems/1.8/gems/passenger-2.2.9/lib/phusion_passenger/abstract_server.rb:352:in `__send__'
    /usr/lib/ruby/gems/1.8/gems/passenger-2.2.9/lib/phusion_passenger/abstract_server.rb:352:in `main_loop'
    /usr/lib/ruby/gems/1.8/gems/passenger-2.2.9/lib/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
    /usr/lib/ruby/gems/1.8/gems/passenger-2.2.9/lib/phusion_passenger/abstract_server.rb:163:in `start'
    /usr/lib/ruby/gems/1.8/gems/passenger-2.2.9/lib/phusion_passenger/railz/application_spawner.rb:209:in `start'
    /usr/lib/ruby/gems/1.8/gems/passenger-2.2.9/lib/phusion_passenger/spawn_manager.rb:262:in `spawn_rails_application'
    /usr/lib/ruby/gems/1.8/gems/passenger-2.2.9/lib/phusion_passenger/abstract_server_collection.rb:126:in `lookup_or_add'
    /usr/lib/ruby/gems/1.8/gems/passenger-2.2.9/lib/phusion_passenger/spawn_manager.rb:256:in `spawn_rails_application'
    /usr/lib/ruby/gems/1.8/gems/passenger-2.2.9/lib/phusion_passenger/abstract_server_collection.rb:80:in `synchronize'
    /usr/lib/ruby/gems/1.8/gems/passenger-2.2.9/lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
    /usr/lib/ruby/gems/1.8/gems/passenger-2.2.9/lib/phusion_passenger/spawn_manager.rb:255:in `spawn_rails_application'
    /usr/lib/ruby/gems/1.8/gems/passenger-2.2.9/lib/phusion_passenger/spawn_manager.rb:154:in `spawn_application'
    /usr/lib/ruby/gems/1.8/gems/passenger-2.2.9/lib/phusion_passenger/spawn_manager.rb:287:in `handle_spawn_application'
    /usr/lib/ruby/gems/1.8/gems/passenger-2.2.9/lib/phusion_passenger/abstract_server.rb:352:in `__send__'
    /usr/lib/ruby/gems/1.8/gems/passenger-2.2.9/lib/phusion_passenger/abstract_server.rb:352:in `main_loop'
    /usr/lib/ruby/gems/1.8/gems/passenger-2.2.9/lib/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
    /usr/lib/ruby/gems/1.8/gems/passenger-2.2.9/bin/passenger-spawn-server:61

Processing ErrorReportsController#create (for 80.187.111.254 at 2010-09-06 16:11:23) [POST]
  Parameters: {"error_report"=>{"body"=>"Version: 1.75dev\n\nInternal Server Error while uploading '咾哎哮:\nBEGIN:VCARD\r\nVERSION:3.0\r\nFN:咾哎哮\r\nN:咾哎哮\r\nTEL;TYPE=CELL:0170234567\r\nTEL;TYPE=CELL:0170234567\r\nTEL;TYPE=CELL:0170234567\r\nADR;TYPE=HOME:;;咾;咾;;咾;咾\r\nADR;TYPE=HOME:;;咾;咾;;咾;咾\r\nADR;TYPE=HOME:;;咾;咾;;咾;咾\r\nEMAIL;TYPE=HOME:咾咿@gmail.com\r\nEMAIL;TYPE=HOME:咾咿@gmail.com\r\nEMAIL;TYPE=HOME:咾咿@gmail.com\r\nEND:VCARD' to http://beta.hoccer.com/uploads/8cc270609bee012dbfd100176ed99fe3"}}
Completed in 3ms (View: 0, DB: 1) | 200 OK [http://beta.hoccer.com/error_reports]
</code></pre>

**Comment by rodja** [comment]
Robert hatte die gute Idee, das das evtl. an unserem VCard-Parsing Hack liegen könnte den wir für die ADC 2 Version im letzten Sommer eingebaut hatten. Ist der noch drin?
